//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_CK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceUsage
    {
        public int Id { get; set; }
        public int ReservationId { get; set; }
        public int ServiceId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual ServiceList ServiceList { get; set; }
    }
}
